### ISSUE TITLE
containerClassName is not updating after change

### ISSUE THREAD

**Issue by Nataron** [alexkatz/react-tiny-popover#78]
Hi, I like your lib and its works fantastic.
One problem I found is that `containerClassName ` is not updated in `ComponentDidUpdate`. This is small change so if someone could add it to his changes I would really appreciate it.
Thanks

**Comment by alexkatz** [comment]
Fixed in latest update!

**Comment by SPavelV** [comment]
I updated to version 6, the problem remains, the containerClassName is not update after passing the new name to this props
![2021-02-03_09-52-53](https://user-images.githubusercontent.com/7521394/106704367-72185900-6605-11eb-88e4-faf658dba18d.png)
![2021-02-03_09-53-14](https://user-images.githubusercontent.com/7521394/106704380-780e3a00-6605-11eb-9299-d50086a0f476.png)
